### ISSUE TITLE
How do I install this on a react-native project ?

### ISSUE THREAD

**Issue by TransLover** [devCracker/ScreenGuard-iOS#1]
I have been trying to find this out for hours, I love the article and that you spent time on this, I truly appreciate that!, but a little more documentation on installation and usage would reeeeeally be helpful!

**Comment by devCracker** [comment]
hi @lg9302 , currently it can not be used directly to react native project. may be you can extend the concept to implement in react native project.

**Comment by Praveencena88** [comment]
@TransLover Did you manage achieve it for react-native?
