### ISSUE TITLE
ionic hierachy issue?

### ISSUE THREAD

**Issue by winnievips** [devCracker/ScreenGuard-iOS#2]
Hi there,

I am working on ionic project requiring this features
now i am able to screenshot and show black screen (means the screen guard works)
i can see my page (not black screen)
but i am unable to tap on my screen.

don't know what info should i provide and how should i resolve it?
any suggestions? thanks

**Comment by devCracker** [comment]
Hi Winnie,  This screenguard is not supporting ionic projects, glad that somehow it works. If you could elaborate bit more on your issue, i may be think and share some lights on that.

**Comment by devCracker** [comment]
as there is no followup conversations, closing this issue
